name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change dir
      run: cd 3-2_Make/
    - name: make
      run: make all
    - name: clean
      run: make clean
