name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List dirs
      run: ls
    - name: Run make
      run: |
        cd 3-2_Make/
        ls
        make all
    - name: Run clean
      run: |
        cd 3-2_Make/
        ls
        make clean
